### ISSUE TITLE
segmentation faults

### ISSUE THREAD

**Issue by james-daily** [yumeng5/CatE#1]
I get fairly frequent segmentation faults, particularly when using larger datasets.

```
Thread 298 "cate" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff96ffd700 (LWP 13498)]
0x000000000040bb95 in TrainEmb (id=0x8) at cate.c:726
726	                    else g = (label - expTable[(int) ((f + MAX_EXP) * (EXP_TABLE_SIZE / MAX_EXP / 2))]) * alpha;
```

This is on Amazon Linux 2.  I assume that what's happening here is that `((f + MAX_EXP) * (EXP_TABLE_SIZE / MAX_EXP / 2))` is sometimes larger than `EXP_TABLE_SIZE`.

**Comment by yumeng5** [comment]
Hi James,

Thanks for posting this issue. Could you provide more contexts like how large your dataset is? Since you mentioned that the error is related to the dataset size, I was wondering if the number of lines in your file (which should be equal to the number of documents) is larger than `corpus_max_size` defined here?
https://github.com/yumeng5/CatE/blob/4d5e97ea566b659e2a07ee5a1c9773608a869a93/src/cate.c#L20
If so, you can change this number to be bigger than the number of documents in your corpus and re-run the code to see if the issue can be fixed.

Best,
Yu

**Comment by james-daily** [comment]
There are 33k documents in the corpus, approximately 7.4M words, and 106M characters.  The longest token is 217 characters.

**Comment by james-daily** [comment]
I turned off compiler optimizations and loaded a core dump in gdb.  The immediate problem seems to be that `syn0` sometimes contains `nan` values (e.g. `syn0[0 + l1]`, `syn0[1 + l1]`, etc are all `nan`). This causes `f` to become `nan`, so in this if/else if/else

```C
if (f > MAX_EXP) g = (label - 1) * alpha;
else if (f < -MAX_EXP) g = (label - 0) * alpha;
else g = (label - expTable[(int) ((f + MAX_EXP) * (EXP_TABLE_SIZE / MAX_EXP / 2))]) * alpha;
```

`expTable[(int) ((f + MAX_EXP) * (EXP_TABLE_SIZE / MAX_EXP / 2))]` becomes `expTable[(int) nan]` which is (on my machine) `expTable[-2112027664]`.

That is about the limit of my understanding of the code, though.

Interestingly, the problem usually (but not always) goes away if I run `cate` in `gdb`.  But if I run the program normally then I usually get a core dump.

I tried analyzing the program with valgrind but got an unrecognized instruction error during one of the initialization stages, so unfortunately that was not helpful.

**Comment by james-daily** [comment]
I believe the problem does not occur when running in `gdb` because `gdb` disables address space randomization by default.  So it is likely that the program is still trying to access `expTable[-2112027664]` but that address is at least within the program's address space.  The value is almost certainly not correct, but it doesn't crash.

I'm not sure what should be done to ensure that `syn0` does not contain `nan` values, though.  

I ran `cate.c` through `cppcheck` and it found only these issues:
```
cate.c:228:9: error: Common realloc mistake: 'vocab' nulled but not freed upon failure [memleakOnRealloc]
        vocab = (struct vocab_word *) realloc(vocab, vocab_max_size * sizeof(struct vocab_word));
        ^
cate.c:271:5: error: Common realloc mistake: 'vocab' nulled but not freed upon failure [memleakOnRealloc]
    vocab = (struct vocab_word *) realloc(vocab, (vocab_size + 1) * sizeof(struct vocab_word));
    ^
cate.c:519:5: error: Common realloc mistake: 'topics' nulled but not freed upon failure [memleakOnRealloc]
    topics = (struct topic *) realloc(topics, num_topic * sizeof(struct topic));
    ^
```

I hope some of this is helpful!

**Comment by james-daily** [comment]
I have tried several variations and found that this error tends to occur at the end of pretraining.  It occurs whether or not I use a pre-trained embedding file.  I have tried increasing all of the parameters (e.g. `MAX_STRING`) but that did not help.

We would really like to try this approach, as our early results were pretty good.  If there's anything else I can provide (a core dump, a sample of the data, etc) please let me know.

**Comment by james-daily** [comment]
Using this guide

https://berthub.eu/fp/

I was able to find the origin of the `NaN` value.  It first shows up in `TopicEmb()`

```
597: exp_list[k] = exp(f);
```

Specifically at this point f == 89.8459778, and exp(89.84) overflows the range of a float.

Maybe it’s a combination of a high dimension (300) and a large number of topics (208)?

In any case, expanding `real` from `float` to `double` seems to resolve the issue.

**Comment by apurvsinghgautam** [comment]
I am also getting a segment fault for my dataset. My dataset includes 28k documents, 9.7M words, 67M characters. I tried changing float to double as suggested by @james-daily, but I am still getting the segmentation fault.

**Comment by yumeng5** [comment]
Hi @apurvsinghgautam,

Thanks for posting the issue. Could you let me know if you are able to run the example datasets (nyt and yelp) without any problem? Also, how many categories are you using (i.e., number of lines in your topic.txt)?

Best,
Yu

**Comment by apurvsinghgautam** [comment]
Yes, I am able to run the NYT dataset successfully. For my dataset, I have 21 lines in my topic.txt. The model sometimes segment faults at around 10-20% and sometimes at about 60-80%

**Comment by yumeng5** [comment]
Thanks for the information. 20 topics should not be a problem. Perhaps it's related to your corpus. Maybe you can first try to omit the argument `-topic-name` (i.e., not providing any category names, in which case the algorithm trains unsupervised embeddings). If the segfault still occurs, then it's very likely that something in the corpus causes the problem. If this is the case, first check if your input text corpus has any empty lines. After that, set `-iter` to be 1 so that the algorithm runs only once on the corpus and it's easier to figure out where the problem occurs. You can then run the algorithm on different portions of the corpus (first half, second half, etc.) and see which portion leads to the issue. 

Thanks,
Yu

**Comment by apurvsinghgautam** [comment]
I tried without -topic-name and the segment fault still occurs. I think it is because of the data set. I did have some lines with empty texts and I rectified it. I ran the code again but then also I get segment fault. From the analysis of the words per line in my phrase_text.txt, I see there are many with just 1 or 2 phrases. I wonder if this is causing the segment fault (having low number of phrases per line)

**Comment by yumeng5** [comment]
Yes, that's possible. If all words in a line are out-of-vocabulary, that line is equivalent to an empty line and may cause an error. The default `-min-count` is 5 which means that any word that appears less than 5 times in the corpus will not appear in the vocabulary and will be ignored during embedding training. You'd better get rid of very short lines in the input file to avoid errors. Also, the algorithm assumes that each line is a sentence/document, which should not be too short.

Best,
Yu

**Comment by apurvsinghgautam** [comment]
These are the things that I did so far and the results that I got. I had 4 datasets which, when combined, I was running on CatE code. The first thing that I did was to run the code with separate datasets and see which one is giving error. Using this, I removed 2 datasets and had 2 datasets with me, which ran successfully without -topic-name parameter. Now I combined these two datasets, and it ran successfully.
The next step was to run it with -topic-name parameter, and when I ran it for default 10 iterations, it gave me segmentation fault. Then I started running it from 1 iteration until 10 iterations to see where the error begins. From this, for iteration 7 and above, I get the segmentation fault. I still don't know what is going wrong there, but I think I will run for iteration 6 or below only.

**Comment by yumeng5** [comment]
Thanks for the information. Then it's more likely to be a category-specific optimization issue. Could you change the `topic_lambda` value defined [here](https://github.com/yumeng5/CatE/blob/68219dca5d2eca6aa38b71653cc78794a9823c47/src/cate.c#L74) to a lower value (e.g. `10` or `5`) and see if it solves the issue? Maybe it's because the category vectors update steps are too big.

**Comment by apurvsinghgautam** [comment]
If I am setting the topic_lambda to 5, then it fixes the issue. For 10, also it gives segmentation fault.
