### ISSUE TITLE
Max n categories for corpus

### ISSUE THREAD

**Issue by petulla** [yumeng5/CatE#2]
I'm just wondering before generating a label set: What is the max n of categories possible for training embeddings a corpus (say of size d with 500-1000 tokens per document)? Is there a simple heuristic?

Thanks

**Comment by yumeng5** [comment]
For the maximum number of categories, although there is not an upper bound, the provided categories are assumed to be semantically separable. So if you have a very large number of categories (hundreds of), there are usually some overlapping categories which will likely have negative impacts on the embedding quality. Practically, we've tried running the code with >50 categories and the results look fine. You can definitely try more categories and see if the results are still reasonable. 

The algorithm will learn the embeddings for every token in the vocabulary (not just those that are assigned to the topics), as well as the embeddings to represent topics, so it is convenient to compare the semantics of every token with every topic via embedding similarity.

Thanks,
Yu

**Comment by petulla** [comment]
Thanks. The concept of overlap here isn't entirely clear to me as obviously both countries have many of the same features (police, education system, sports etc..), even if at the entity-level there are more distinctions. 

I will try this again. Have you tried learning over subwords (similar to fasttext)?

**Comment by yumeng5** [comment]
Thanks. You are right that there is not a clear distinction of separable vs. non-separable concepts--it's pretty much depending on whether or not the corpus contains contexts that can distinguish two countries. So the best way would always be to first try it and see if the algorithm generates feasible outputs.

As for subwords, the code doesn't support subword embedding learning now (although technically the algorithm can be adapted to subword embeddings). If you have a corpus that is already segmented into subwords, you can directly run CatE on it to generate subword embeddings. Otherwise, I can't think of easy ways (code-wise) to learn CatE embeddings over subwords.

Thanks,
Yu
