### ISSUE TITLE
Hi Yu meng!

### ISSUE THREAD

**Issue by Weifanwong** [yumeng5/CatE#6]
Hi Yu Meng:

I read your code and noticed that the code is designed as a full batch training model which might be caused by the part of loss considering global contexts. And this might further cause a massive computation complexity when dealing with large corpus with millions even billions of texts.
Do you have any concern or solution to this problem? Recently I'm interested in the supervised topic model and find your paper is really helpful. Thanks for your excellent work!

Best Weifan.

**Comment by Weifanwong** [comment]
Another question, I also noticed that both joSH and CatE are implemented with C. Is there any possible limitation for other language like python to reproduce these model?

Best Weifan.

**Comment by yumeng5** [comment]
Hi Weifan,

Thanks for your interest and I'm sorry for my late response--I've been quite busy recently.

For the first computation complexity question, do you mean the training is in online learning mode (batch size=1) since the gradient update is performed for every word in the current implementation? Could you also elaborate why the computation complexity will be high when the corpus is very large (I believe the computation cost will linearly increase with the size of the corpus, but I haven't tried very large corpora myself, so I'm not entirely sure what will happen)?

Regarding the implementation question, yes we also tried using python for the algorithm, but it turned out that the python implementation was significantly slower than the C implementation. Actually, many word embedding learning algorithms (word2vec, GloVe, fastText, etc.) are written in C/C++ for efficiency, although they may have python wrappers available to be used in a python environment.

I hope my explanations help. Please let me know if you have further questions.

Best,
Yu
